<?php

/**
* Trait CarOwnerTrait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;



trait CarOwnerTrait
{
    
    public function getTable()
    {
        return $this->table ?? 'car_owners';
    }

    public function getFillable()
    {
        return $this->fillable ?? [
                            'id',
                            'created_at',
                            'updated_at',
                            'nume',
                    ];
    }

    }
