<?php
/**
* Trait CarTrait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait CarTrait
{
    
    public function getTable()
    {
        return $this->table ?? 'cars';
    }

    public function getFillable()
    {
        if (!empty($this->fillable)) {
            return $this->fillable;
        }

        return [
                            'id',
                            'created_at',
                            'updated_at',
                            'name',
                            'car_owner_id',
                            'type_id',
                    ];
    }

                        public function car_owner(): \Illuminate\Database\Eloquent\Relations\BelongsTo
            {
                return $this->belongsTo(\App\Models\Owner::class);
            }
                                                public function type(): \Illuminate\Database\Eloquent\Relations\BelongsTo
            {
                return $this->belongsTo(\App\Models\CarType::class);
            }
                            }
