<?php

/**
* Trait CarTrait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;


use App\Models\User;

trait CarTrait
{
    
    public function getTable()
    {
        return $this->table ?? 'cars';
    }

    public function getFillable()
    {
        return $this->fillable ?? [
                            'id',
                            'created_at',
                            'updated_at',
                            'name',
                    ];
    }

                                public function users(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
            {
                return $this->belongsToMany(User::class, 'car_user', 'car_id', 'user_id', 'id', 'id', null);
            }
                    }
