<?php
/**
* Trait CarTypeTrait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait CarTypeTrait
{
    
    public function getTable()
    {
        return $this->table ?? 'car_types';
    }

    public function getFillable()
    {
        if (!empty($this->fillable)) {
            return $this->fillable;
        }

        return [
                            'id',
                            'created_at',
                            'updated_at',
                            'name',
                    ];
    }

                                        public function cars(): \Illuminate\Database\Eloquent\Relations\HasMany
            {
                return $this->hasMany(\App\Models\Car::class, 'car_type_id', 'id');
            }
                                                public function cars(): \Illuminate\Database\Eloquent\Relations\HasMany
            {
                return $this->hasMany(\App\Models\Car::class, 'car_type_id', 'id');
            }
            }
