<?php
/**
* Trait DealerTrait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait DealerTrait
{
    
    public function getTable()
    {
        return $this->table ?? 'dealers';
    }

    public function getFillable()
    {
        if (!empty($this->fillable)) {
            return $this->fillable;
        }

        return [
                            'status',
                            'status2',
                            'status3',
                    ];
    }

    }
