<?php
/**
* Trait OwnerTrait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait OwnerTrait
{
    
    public function getTable()
    {
        return $this->table ?? 'owners';
    }

    public function getFillable()
    {
        if (!empty($this->fillable)) {
            return $this->fillable;
        }

        return [
                            'id',
                            'created_at',
                            'updated_at',
                            'name',
                    ];
    }

    }
