<?php

/**
* Trait UserTrait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

use Illuminate\Database\Eloquent\SoftDeletes;

use App\Models\Car;

trait UserTrait
{
            use SoftDeletes;
    
    public function getTable()
    {
        return $this->table ?? 'users';
    }

    public function getFillable()
    {
        return $this->fillable ?? [
                            'id',
                            'name',
                            'email',
                            'email_verified_at',
                            'password',
                            'created_at',
                            'updated_at',
                            'deleted_at',
                    ];
    }

                                public function cars(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
            {
                return $this->belongsToMany(Car::class, 'car_user', 'user_id', 'car_id', 'id', 'id', null);
            }
                    }
