<div>
    <table class="mt-6 w-full">
                    <tr>
                <th class="text-left">
                    id
                </th>
                <td>
                    @includeFirst(
                        [
                        'admin.crud-controller.usercontroller.show.id',
                        'admin.generated.crud-controller.usercontroller.show.id'
                        ]
                    )
                </td>
            </tr>
                    <tr>
                <th class="text-left">
                    name
                </th>
                <td>
                    @includeFirst(
                        [
                        'admin.crud-controller.usercontroller.show.name',
                        'admin.generated.crud-controller.usercontroller.show.name'
                        ]
                    )
                </td>
            </tr>
                    <tr>
                <th class="text-left">
                    email
                </th>
                <td>
                    @includeFirst(
                        [
                        'admin.crud-controller.usercontroller.show.email',
                        'admin.generated.crud-controller.usercontroller.show.email'
                        ]
                    )
                </td>
            </tr>
                    <tr>
                <th class="text-left">
                    email_verified_at
                </th>
                <td>
                    @includeFirst(
                        [
                        'admin.crud-controller.usercontroller.show.email_verified_at',
                        'admin.generated.crud-controller.usercontroller.show.email_verified_at'
                        ]
                    )
                </td>
            </tr>
                    <tr>
                <th class="text-left">
                    password
                </th>
                <td>
                    @includeFirst(
                        [
                        'admin.crud-controller.usercontroller.show.password',
                        'admin.generated.crud-controller.usercontroller.show.password'
                        ]
                    )
                </td>
            </tr>
                    <tr>
                <th class="text-left">
                    created_at
                </th>
                <td>
                    @includeFirst(
                        [
                        'admin.crud-controller.usercontroller.show.created_at',
                        'admin.generated.crud-controller.usercontroller.show.created_at'
                        ]
                    )
                </td>
            </tr>
                    <tr>
                <th class="text-left">
                    updated_at
                </th>
                <td>
                    @includeFirst(
                        [
                        'admin.crud-controller.usercontroller.show.updated_at',
                        'admin.generated.crud-controller.usercontroller.show.updated_at'
                        ]
                    )
                </td>
            </tr>
                    <tr>
                <th class="text-left">
                    deleted_at
                </th>
                <td>
                    @includeFirst(
                        [
                        'admin.crud-controller.usercontroller.show.deleted_at',
                        'admin.generated.crud-controller.usercontroller.show.deleted_at'
                        ]
                    )
                </td>
            </tr>
            </table>
</div>
